import type {
  CacheStatus,
  Events,
  LaunchDetail,
  Launches,
  StarlinkSummary,
} from '../types'

export const launchesFixture: Launches = {
  total: 127,
  stale: false,
  sampled: false,
  results: [
    {
      id: 'launch-1',
      sourceUrl: 'https://ll.thespacedevs.com/2.2.0/launch/launch-1/',
      name: 'Falcon Heavy | Roman Space Telescope',
      status: {
        name: 'Go for Launch',
        abbrev: 'Go',
        description: 'T-0 confirmed by reliable sources.',
      },
      lastUpdated: '2026-08-28T14:50:34Z',
      net: '2030-08-30T11:26:00Z',
      windowStart: '2030-08-30T11:26:00Z',
      windowEnd: '2030-08-30T11:26:00Z',
      precision: {
        name: 'Minute',
        abbrev: 'MIN',
        description: 'Accurate to the minute.',
      },
      probability: 60,
      weatherConcerns: 'Cumulus Cloud Rule',
      holdReason: null,
      failReason: null,
      provider: 'SpaceX',
      rocket: 'Falcon Heavy',
      rocketFamily: 'Falcon',
      missionName: 'Roman Space Telescope',
      missionDescription: 'A NASA infrared space telescope mission.',
      missionType: 'Astrophysics',
      orbit: 'Sun-Earth L2',
      orbitAbbrev: 'L2',
      pad: 'Launch Complex 39A',
      location: 'Kennedy Space Center, FL, USA',
      latitude: 28.6082,
      longitude: -80.6042,
      webcastLive: false,
      imageUrl: null,
    },
    {
      id: 'launch-2',
      sourceUrl: 'https://ll.thespacedevs.com/2.2.0/launch/launch-2/',
      name: 'Falcon 9 | Starlink Group',
      status: {
        name: 'To Be Confirmed',
        abbrev: 'TBC',
        description: 'Awaiting confirmation.',
      },
      lastUpdated: '2026-08-27T14:50:34Z',
      net: '2030-09-02T07:46:00Z',
      windowStart: '2030-09-02T07:46:00Z',
      windowEnd: '2030-09-02T11:46:00Z',
      precision: {
        name: 'Minute',
        abbrev: 'MIN',
        description: 'Accurate to the minute.',
      },
      probability: null,
      weatherConcerns: null,
      holdReason: null,
      failReason: null,
      provider: 'SpaceX',
      rocket: 'Falcon 9 Block 5',
      rocketFamily: 'Falcon',
      missionName: 'Starlink Group 15-23',
      missionDescription: 'A batch of satellites for the Starlink constellation.',
      missionType: 'Communications',
      orbit: 'Low Earth Orbit',
      orbitAbbrev: 'LEO',
      pad: 'Space Launch Complex 4E',
      location: 'Vandenberg SFB, CA, USA',
      latitude: 34.632,
      longitude: -120.611,
      webcastLive: false,
      imageUrl: null,
    },
  ],
}

export const eventsFixture: Events = {
  total: 1,
  stale: false,
  sampled: false,
  results: [
    {
      id: 1512,
      sourceUrl: 'https://ll.thespacedevs.com/2.2.0/event/1512/',
      name: 'Starship Booster Static Fire',
      type: 'Static Fire',
      description: 'A booster static fire ahead of the next flight.',
      date: '2030-08-29T18:10:00Z',
      precision: 'Minute',
      location: 'Starbase Texas',
      webcastLive: false,
      videoUrl: 'https://example.com/watch',
      newsUrl: null,
      imageUrl: null,
      lastUpdated: '2026-08-28T19:41:11Z',
    },
  ],
}

export const launchDetailFixture: LaunchDetail = {
  ...launchesFixture.results[0],
  flightClubUrl: 'https://flightclub.io/result?llId=launch-1',
  rocketDetails: {
    description: 'A heavy-lift launch vehicle with reusable side boosters.',
    reusable: true,
    lengthMeters: 70,
    diameterMeters: 12.2,
    launchCostUsd: 90_000_000,
    leoCapacityKg: 63_800,
    gtoCapacityKg: 26_700,
    launches: 12,
    successes: 12,
    infoUrl: 'https://example.com/rocket',
    wikiUrl: 'https://example.com/wiki',
  },
  stages: [
    {
      type: 'Strap-On Booster',
      serialNumber: 'B1072',
      details: 'Flight-proven side booster.',
      reused: true,
      flightNumber: 3,
      landing: {
        attempted: true,
        description: 'Return to the launch site.',
        type: 'Return to Launch Site',
        location: 'Landing Zone 2',
      },
    },
  ],
  padDetails: {
    description: 'Historic launch complex.',
    mapUrl: 'https://example.com/map',
    wikiUrl: 'https://example.com/pad',
  },
  links: [
    {
      title: 'Official mission page',
      description: 'SpaceX mission page.',
      url: 'https://example.com/mission',
      source: 'spacex.com',
      type: 'Official Page',
    },
  ],
  videos: [
    {
      title: 'Official webcast',
      description: 'Mission webcast.',
      url: 'https://example.com/watch',
      source: 'youtube.com',
      type: 'Official Webcast',
      startsAt: '2030-08-30T10:20:00Z',
    },
  ],
  timeline: [
    {
      label: 'Liftoff',
      description: 'First upward movement.',
      relativeTime: 'P0D',
    },
  ],
  updates: [
    {
      comment: 'Updated launch weather, 60% GO.',
      url: 'https://example.com/weather',
      createdAt: '2026-08-28T14:50:00Z',
    },
  ],
}

export const starlinkFixture: StarlinkSummary = {
  fetchedAt: '2026-08-28T20:22:31Z',
  calculatedAt: '2026-08-28T20:30:00Z',
  stale: false,
  sampled: false,
  count: 8_100,
  newestEpoch: '2026-08-28T14:45:00Z',
  averageInclination: 53.1,
  averageAltitudeKm: 550,
  averagePeriodMinutes: 95.3,
  inclinationBands: [{ inclination: 53, count: 7_000 }],
  plot: [
    { id: 44714, name: 'STARLINK-1008', raan: 79.083, inclination: 53.1472, anomaly: 273.4651 },
    { id: 44718, name: 'STARLINK-1012', raan: 179.3849, inclination: 53.1497, anomaly: 159.6021 },
  ],
  positions: [
    {
      id: 44714,
      name: 'STARLINK-1008',
      latitude: 42.5,
      longitude: -64.2,
      altitudeKm: 532,
    },
    {
      id: 44718,
      name: 'STARLINK-1012',
      latitude: -18.4,
      longitude: 121.6,
      altitudeKm: 530,
    },
  ],
  satellites: [
    {
      name: 'STARLINK-1008',
      objectId: '2019-074B',
      noradId: 44714,
      epoch: '2026-08-28T13:44:26Z',
      inclination: 53.1472,
      eccentricity: 0.00037588,
      periodMinutes: 92.18,
      altitudeKm: 532,
    },
  ],
}

export const cacheStatusFixture: CacheStatus = {
  sources: [
    {
      key: 'll2:launches',
      label: 'LL2 launches',
      fetchedAt: '2026-08-28T20:22:31Z',
      refreshAfter: '2026-08-28T20:32:31Z',
      sizeBytes: 12_450,
      fresh: false,
      nextAttemptAt: '2030-08-28T21:22:31Z',
      nextAttemptReason: 'LL2 rate-limit window',
    },
    {
      key: 'll2:events',
      label: 'LL2 events',
      fetchedAt: null,
      refreshAfter: null,
      sizeBytes: 0,
      fresh: false,
      nextAttemptAt: '2030-08-28T20:30:00Z',
      nextAttemptReason: 'Next dashboard request',
    },
    {
      key: 'celestrak:starlink',
      label: 'CelesTrak Starlink',
      fetchedAt: '2026-08-28T20:22:31Z',
      refreshAfter: '2026-08-28T22:22:31Z',
      sizeBytes: 805_000,
      fresh: true,
      nextAttemptAt: '2030-08-28T22:22:31Z',
      nextAttemptReason: 'Cache freshness window',
    },
  ],
  missionDetailsStored: 2,
}
